/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package placement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class editperdetails extends javax.swing.JFrame {

    /** Creates new form editperdetails */
    String username;
    public String name;
    public Long prn;
    public String gen;
    public Long ph;
    public String em;
    public String dept;
    public editperdetails() {
        setUndecorated(true);
        initComponents();
        PreparedStatement ps;
        ResultSet rs;
        String sql = "SELECT loginID FROM `login` WHERE sr=1";
        try{
            ps = myconnection.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            if(rs.next()){
                username=rs.getString(1);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        PreparedStatement pstmt;
        ResultSet r;
        String query = "SELECT Name,PRN,Gender,Phone,Email,Department from studentlogin WHERE username= '"+username+"'";
        try{
            pstmt = myconnection.getConnection().prepareStatement(query);
            r=pstmt.executeQuery();
            if(r.next()){
                name = r.getString(1);
                prn = r.getLong(2);
                gen = r.getString(3);
                ph = r.getLong(4);
                em = r.getString(5);
                dept = r.getString(6);
                namefld.setText(name);
                prnfld.setText(Long.toString(prn));
                genderfld.setText(gen);
                contactfld.setText(Long.toString(ph));
                emailfld.setText(em);
                deptfld.setText(dept);
            }
        }catch(Exception es){
            JOptionPane.showMessageDialog(null, es);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        PRNlbl = new javax.swing.JLabel();
        genderlbl = new javax.swing.JLabel();
        contatlbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        deptlbl = new javax.swing.JLabel();
        deptfld = new javax.swing.JTextField();
        emailfld = new javax.swing.JTextField();
        contactfld = new javax.swing.JTextField();
        genderfld = new javax.swing.JTextField();
        prnfld = new javax.swing.JTextField();
        namefld = new javax.swing.JTextField();
        doblbl = new javax.swing.JLabel();
        dobfld = new javax.swing.JTextField();
        applybtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PERSONAL DETAILS");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        namelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namelbl.setText("NAME");
        jPanel2.add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        PRNlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PRNlbl.setText("PRN");
        jPanel2.add(PRNlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        genderlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderlbl.setText("GENDER");
        jPanel2.add(genderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        contatlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contatlbl.setText("PHONE NO.");
        jPanel2.add(contatlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        emaillbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaillbl.setText("EMAIL ID");
        jPanel2.add(emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        deptlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deptlbl.setText("DEPARTMENT");
        jPanel2.add(deptlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        deptfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deptfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptfldActionPerformed(evt);
            }
        });
        jPanel2.add(deptfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 431, 200, -1));

        emailfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(emailfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 387, 200, -1));

        contactfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(contactfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 343, 200, -1));

        genderfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(genderfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 299, 200, -1));

        prnfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prnfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prnfldActionPerformed(evt);
            }
        });
        jPanel2.add(prnfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 255, 200, -1));

        namefld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(namefld, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 211, 200, -1));

        doblbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doblbl.setText("DOB");
        jPanel2.add(doblbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        dobfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dobfld.setToolTipText("Format DD/MM/YYYY. Put '/' also.");
        dobfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobfldActionPerformed(evt);
            }
        });
        jPanel2.add(dobfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 475, 200, -1));

        applybtn.setBackground(new java.awt.Color(255, 51, 51));
        applybtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        applybtn.setForeground(new java.awt.Color(255, 255, 255));
        applybtn.setText("Apply");
        applybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applybtnActionPerformed(evt);
            }
        });
        jPanel2.add(applybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deptfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptfldActionPerformed

    private void prnfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prnfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prnfldActionPerformed

    private void dobfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobfldActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void applybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applybtnActionPerformed
        // TODO add your handling code here:
        if(dobfld.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Enter DOB!!");
        }
        else{
            name=namefld.getText();
            prn=Long.parseLong(prnfld.getText());
            em=emailfld.getText();
            gen=genderfld.getText();
            dept=deptfld.getText();
            ph=Long.parseLong(contactfld.getText());
            String dob = dobfld.getText();
            String sql="update studentlogin set Name='"+name+"', PRN='"+prn+"', Email='"+em+"', Gender='"+gen+"', Department='"+dept+"', Phone='"+ph+"',DOB='"+dob+"' where username='"+username+"'";
        try{
            PreparedStatement ps;
            ps = myconnection.getConnection().prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Edited Successfully!!");
        }catch(Exception es){
            Logger.getLogger(startupScreen.class.getName()).log(Level.SEVERE, null, es);
        }
        WelcomeStudent lgf=new WelcomeStudent();
        lgf.setVisible(true);
        lgf.setLocationRelativeTo(null);
        this.dispose();
        }
    }//GEN-LAST:event_applybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editperdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editperdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editperdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editperdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editperdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PRNlbl;
    private javax.swing.JButton applybtn;
    public javax.swing.JTextField contactfld;
    private javax.swing.JLabel contatlbl;
    public javax.swing.JTextField deptfld;
    private javax.swing.JLabel deptlbl;
    public javax.swing.JTextField dobfld;
    private javax.swing.JLabel doblbl;
    public javax.swing.JTextField emailfld;
    private javax.swing.JLabel emaillbl;
    public javax.swing.JTextField genderfld;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField namefld;
    private javax.swing.JLabel namelbl;
    public javax.swing.JTextField prnfld;
    // End of variables declaration//GEN-END:variables

}
