/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class registerStud extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public registerStud() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        PRNlbl = new javax.swing.JLabel();
        genderlbl = new javax.swing.JLabel();
        contatlbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        deptlbl = new javax.swing.JLabel();
        usernamelbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        retypelbl = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JButton();
        namefld = new javax.swing.JTextField();
        prnfld = new javax.swing.JTextField();
        genderfld = new javax.swing.JTextField();
        contactfld = new javax.swing.JTextField();
        emailfld = new javax.swing.JTextField();
        deptfld = new javax.swing.JTextField();
        usernamefld = new javax.swing.JTextField();
        passwordfld = new javax.swing.JPasswordField();
        repassfld = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("SIGN UP");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText(" X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        namelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namelbl.setText("NAME");

        PRNlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PRNlbl.setText("PRN");

        genderlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderlbl.setText("GENDER");

        contatlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contatlbl.setText("PHONE NO.");

        emaillbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaillbl.setText("EMAIL ID");

        deptlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deptlbl.setText("DEPARTMENT");

        usernamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernamelbl.setText("SET USERNAME");

        passwordlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordlbl.setText("SET PASSWORD");

        retypelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        retypelbl.setText("CONFIRM PASSWORD");

        RegisterBtn.setBackground(new java.awt.Color(255, 51, 51));
        RegisterBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setText("REGISTER");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        namefld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        prnfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prnfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prnfldActionPerformed(evt);
            }
        });

        genderfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        contactfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        emailfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        deptfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deptfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptfldActionPerformed(evt);
            }
        });

        usernamefld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        passwordfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        repassfld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namelbl)
                    .addComponent(PRNlbl)
                    .addComponent(genderlbl)
                    .addComponent(contatlbl)
                    .addComponent(emaillbl)
                    .addComponent(deptlbl)
                    .addComponent(usernamelbl)
                    .addComponent(passwordlbl)
                    .addComponent(retypelbl))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namefld)
                    .addComponent(prnfld)
                    .addComponent(genderfld)
                    .addComponent(contactfld)
                    .addComponent(emailfld)
                    .addComponent(deptfld)
                    .addComponent(usernamefld)
                    .addComponent(passwordfld)
                    .addComponent(repassfld, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(RegisterBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl)
                    .addComponent(namefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRNlbl)
                    .addComponent(prnfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderlbl)
                    .addComponent(genderfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contatlbl)
                    .addComponent(contactfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillbl)
                    .addComponent(emailfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptlbl)
                    .addComponent(deptfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelbl)
                    .addComponent(usernamefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlbl)
                    .addComponent(passwordfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retypelbl)
                    .addComponent(repassfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(RegisterBtn)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prnfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prnfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prnfldActionPerformed

    private void deptfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptfldActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        String pass=passwordfld.getText();
        String rePass=repassfld.getText();
        if(pass.equals(rePass)){
            try{
                Statement stmt= myconnection.getConnection().createStatement();
                String query = "SELECT * FROM studentlogin WHERE username='" + usernamefld.getText() + "'";
                ResultSet rs = stmt.executeQuery(query);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Username already taken!");
                }
                else{
                    String sql = "insert into studentlogin(`Name`, `PRN`, `Email`, `Gender`, `username`, `pass`, `Department`, `Phone`) values (? ,?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement pstmt = myconnection.getConnection().prepareStatement(sql);
                    pstmt.setString(5, usernamefld.getText());
                    pstmt.setString(6,passwordfld.getText());
                    pstmt.setString(1, namefld.getText());
                    pstmt.setLong(2,Long.parseLong(prnfld.getText()));
                    pstmt.setString(3, emailfld.getText());
                    pstmt.setString(4, genderfld.getText());
                    pstmt.setString(7, deptfld.getText());
                    pstmt.setLong(8, Long.parseLong(contactfld.getText()));
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Registered Successfully!!");
                    login lgf=new login();
                    lgf.setVisible(true);
                    this.dispose();
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }else
            JOptionPane.showMessageDialog(null, "Passwords don't match!!");
    }//GEN-LAST:event_RegisterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerStud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PRNlbl;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JTextField contactfld;
    private javax.swing.JLabel contatlbl;
    private javax.swing.JTextField deptfld;
    private javax.swing.JLabel deptlbl;
    private javax.swing.JTextField emailfld;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField genderfld;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namefld;
    private javax.swing.JLabel namelbl;
    private javax.swing.JPasswordField passwordfld;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JTextField prnfld;
    private javax.swing.JPasswordField repassfld;
    private javax.swing.JLabel retypelbl;
    private javax.swing.JTextField usernamefld;
    private javax.swing.JLabel usernamelbl;
    // End of variables declaration//GEN-END:variables
}
