/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class WelcomeCompany extends javax.swing.JFrame {

    /**
     * Creates new form WeclomeCompany
     */
    String com;
    String username;
    public WelcomeCompany() {
        setUndecorated(true);
        initComponents();
        PreparedStatement pt;
        ResultSet r;
        String sql = "SELECT loginID FROM `login` WHERE sr=1";
        try{
            pt = myconnection.getConnection().prepareStatement(sql);
            r = pt.executeQuery();
            if(r.next()){
                username=r.getString(1);
                PreparedStatement pstmt;
                ResultSet rt;
                String s="SELECT Name FROM company WHERE user='"+username+"'";
                try{
                    pstmt = myconnection.getConnection().prepareStatement(s);
                    rt=pstmt.executeQuery();
                    if(rt.next()){
                        com=rt.getString(1);
                        Welcomelbl.setText("Welcome, "+com+"!!!");
                    }
                }catch(Exception et){
                    JOptionPane.showMessageDialog(null, et);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Welcomelbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listbtn = new javax.swing.JButton();
        resultbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        schedulebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(641, 479));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcomelbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel2.add(Welcomelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 530, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 640, -1));

        listbtn.setBackground(new java.awt.Color(255, 51, 51));
        listbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listbtn.setForeground(new java.awt.Color(255, 255, 255));
        listbtn.setText("Check Applied Candidate list");
        listbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listbtnActionPerformed(evt);
            }
        });
        jPanel1.add(listbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        resultbtn.setBackground(new java.awt.Color(255, 51, 51));
        resultbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resultbtn.setForeground(new java.awt.Color(255, 255, 255));
        resultbtn.setText("Check Candidate result");
        resultbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultbtnActionPerformed(evt);
            }
        });
        jPanel1.add(resultbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 225, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 100, -1));

        schedulebtn.setBackground(new java.awt.Color(255, 51, 51));
        schedulebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        schedulebtn.setForeground(new java.awt.Color(255, 255, 255));
        schedulebtn.setText("Schedule Interview");
        schedulebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedulebtnActionPerformed(evt);
            }
        });
        jPanel1.add(schedulebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new thanks().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listbtnActionPerformed
        new checkCandidate().setVisible(true);
    }//GEN-LAST:event_listbtnActionPerformed

    private void schedulebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedulebtnActionPerformed
        new schedule().setVisible(true);
    }//GEN-LAST:event_schedulebtnActionPerformed

    private void resultbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultbtnActionPerformed
        new checkResCom().setVisible(true);
    }//GEN-LAST:event_resultbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcomelbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton listbtn;
    private javax.swing.JButton resultbtn;
    private javax.swing.JButton schedulebtn;
    // End of variables declaration//GEN-END:variables
}
