/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placement;

public class WelcomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeAdmin
     */
    public WelcomeAdmin() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updStudMarkbtn = new javax.swing.JButton();
        checklistbtn = new javax.swing.JButton();
        Checkresultbtn = new javax.swing.JButton();
        signout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(641, 479));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("WELCOME!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 20, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 150));

        updStudMarkbtn.setBackground(new java.awt.Color(255, 51, 51));
        updStudMarkbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updStudMarkbtn.setForeground(new java.awt.Color(255, 255, 255));
        updStudMarkbtn.setText("Update Academic details");
        updStudMarkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updStudMarkbtnActionPerformed(evt);
            }
        });
        jPanel1.add(updStudMarkbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        checklistbtn.setBackground(new java.awt.Color(255, 51, 51));
        checklistbtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        checklistbtn.setForeground(new java.awt.Color(255, 255, 255));
        checklistbtn.setText("Candidate Preference");
        checklistbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checklistbtnActionPerformed(evt);
            }
        });
        jPanel1.add(checklistbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 200, 30));

        Checkresultbtn.setBackground(new java.awt.Color(255, 51, 51));
        Checkresultbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Checkresultbtn.setForeground(new java.awt.Color(255, 255, 255));
        Checkresultbtn.setText("Check Result");
        Checkresultbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckresultbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Checkresultbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 200, -1));

        signout.setBackground(new java.awt.Color(255, 51, 51));
        signout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setText("Sign Out");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        jPanel1.add(signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        new thanks().setVisible(true);
    }//GEN-LAST:event_signoutActionPerformed

    private void updStudMarkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updStudMarkbtnActionPerformed
        new acaddetails().setVisible(true);
    }//GEN-LAST:event_updStudMarkbtnActionPerformed

    private void checklistbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checklistbtnActionPerformed
        new checkcandidateAdmin().setVisible(true);
    }//GEN-LAST:event_checklistbtnActionPerformed

    private void CheckresultbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckresultbtnActionPerformed
        new checkResAd().setVisible(true);
    }//GEN-LAST:event_CheckresultbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Checkresultbtn;
    private javax.swing.JButton checklistbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton signout;
    private javax.swing.JButton updStudMarkbtn;
    // End of variables declaration//GEN-END:variables
}
